services:
  # Your Spring Boot Application
  app:
    build: . # Build from the Dockerfile in the current directory
    container_name: persons_finder_app
    ports:
      - "8080:8080" # Access your app on http://localhost:8080
    environment:
      # These variables will override values in application.properties when running in Docker
      - DEBUG=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/persons_finder
      - SPRING_DATASOURCE_USERNAME=emerge
      - SPRING_DATASOURCE_PASSWORD=emerge
    depends_on:
      - db # Ensure database starts before the app
    restart: unless-stopped # Added restart policy for robustness
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  # PostgreSQL Database with PostGIS
  db:
    image: postgis/postgis:17-3.5 # Official PostGIS image
    container_name: persons_finder_db
    ports:
      - "5432:5432" # Access DB on http://localhost:5432
    environment:
      POSTGRES_DB: persons_finder
      POSTGRES_USER: emerge
      POSTGRES_PASSWORD: emerge
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent data volume
    restart: unless-stopped
    # Optimize db resources for handling queries into a massive data efficiently
    # Primary bottleneck is work_mem - the maximum amount of memory used by a query operation (like sorting or hashing) before it spills to disk
    # Reading and writing to disk is much slower than performing operations in RAM
    command: postgres -c 'shared_buffers=3GB' -c 'work_mem=512MB' -c 'effective_cache_size=6GB' -c 'max_parallel_workers=4' -c 'max_parallel_workers_per_gather=2'
    # Resource Limits for a massive database (up to 100 mln records in the 2 tables)
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G

  # PgAdmin 4
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ui
    ports:
      - "5050:80" # Access PgAdmin UI on http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    restart: unless-stopped

  # Prometheus Monitoring Server
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_server
    ports:
      - "9090:9090" # Access Prometheus UI on http://localhost:9090
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # Mount config
      - prometheus_data:/prometheus # Persistent data volume for metrics
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - app # Prometheus needs app to be running to scrape metrics
    restart: unless-stopped
    # Prometheus will collect a lot more metrics at this scale
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  # Grafana Visualization Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000" # Access Grafana UI on http://localhost:3000
    volumes:
      - grafana_data:/var/lib/grafana # Persistent data volume for Grafana
      # Mount Grafana provisioning configuration for datasources
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      # Mount Grafana provisioning configuration for dashboards
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus # Grafana needs Prometheus to be running as a data source
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 512M
volumes:
  db_data:
  prometheus_data:
  grafana_data: